/**
 * Phase 0 routing spike: route the Edinburgh acceptance journeys with
 * several profiles over the committed snapshot and write a report plus
 * GeoJSON for the viewer.
 *   pnpm spike
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { isKnown, loadSnapshot } from "@causeway/graph/node";
import { PRESETS, type MobilityPreset } from "@causeway/profile";
import { describeSegments, elevationProfile, explain, Router, summarise, toGeoJSON, tradeoffs } from "@causeway/router";
import { EDINBURGH_JOURNEYS } from "./journeys.js";

const ROOT = join(import.meta.dirname, "..");
const g = loadSnapshot(join(ROOT, "data/snapshots/edinburgh-old-town.graph.json.gz"));
const router = new Router(g);
const PROFILES: MobilityPreset[] = ["walking", "manual-wheelchair", "manual-wheelchair-companion", "powerchair"];

const features: unknown[] = [];
const md: string[] = [];
md.push("# Phase 0 routing spike: Edinburgh Old Town", "");
md.push(
  `Generated by \`pnpm spike\` from the committed snapshot \`data/snapshots/edinburgh-old-town.graph.json.gz\` (${g.nodes.length} nodes, ${g.edges.length} edges, built ${g.meta.builtAt.slice(0, 10)}).`,
  "",
  "Data: © OpenStreetMap contributors (ODbL). Terrain: LiDAR for Scotland Phase 5, Open Government Licence v3.0.",
  "",
  "Conditions: dry. Profiles are presets from `packages/profile`; real users set their own limits.",
  "",
);

for (const j of EDINBURGH_JOURNEYS) {
  md.push(`## ${j.title}`, "");
  md.push("| Profile | Time | Distance | Ascent | Steepest | Setts | Steps | Lifts | Unknown | Verdict | Via |", "|---|---|---|---|---|---|---|---|---|---|---|");
  const blocks: string[] = [];
  for (const pre of PROFILES) {
    const p = PRESETS[pre];
    const a = router.snap(j.from.lon, j.from.lat, p);
    const b = router.snap(j.to.lon, j.to.lat, p);
    const r = router.route(a, b, p);
    if (!r) {
      md.push(`| ${p.label} | no route | | | | | | | | not passable | |`);
      continue;
    }
    const s = summarise(r);
    const via = [...new Set(r.steps.map((x) => x.edge.name).filter((n): n is string => !!n && !n.startsWith("Platform")))].join(" / ");
    const setts = (s.surfaceMix["setts"] ?? 0) + (s.surfaceMix["cobbles"] ?? 0);
    md.push(
      `| ${p.label} | ${Math.round(s.minutes)} min | ${s.distanceM} m | ${s.ascentM} m | ${s.worstInclinePct === null ? "unknown" : `${Math.abs(s.worstInclinePct)}% ${s.worstInclinePct >= 0 ? "up" : "down"}`} | ${setts} m | ${s.steps} | ${s.lifts} | ${s.unknownM} m | ${s.verdict} | ${via} |`,
    );
    const ex = explain(router, r, a, b, p, PRESETS.walking);
    const tos = pre === "walking" ? [] : tradeoffs(router, r, a, b, p);
    blocks.push(
      `### ${p.label}`,
      "",
      `**Why this way?** ${ex.headline}`,
      "",
      ...ex.notes.map((n) => `- ${n}`),
      ...(ex.avoided.length
        ? ["", "Avoided on the direct route:", "", ...ex.avoided.slice(0, 6).map((x) => `- ${x.name}: ${x.reason.detail} (${x.reason.kind})`)]
        : []),
      ...(tos.length ? ["", "Trade-offs offered:", "", ...tos.map((t) => `- ${t.label}: ${t.message}`)] : []),
      "",
      "<details><summary>Spoken route (non-visual mode)</summary>",
      "",
      ...describeSegments(r).map((d, i) => `${i + 1}. ${d}`),
      "",
      "</details>",
      "",
    );
    features.push(
      toGeoJSON(r, {
        journey: j.id,
        profile: pre,
        label: p.label,
        ...s,
        headline: ex.headline,
        elevation: elevationProfile(r, a),
      }),
    );
  }
  md.push("", ...blocks);
}

// Coverage of the spike area: the honest-graph headline numbers.
const walkable = g.edges.filter((e) => e.kind !== "elevator");
const total = walkable.reduce((t, e) => t + e.lengthM, 0);
const pct = (f: (e: (typeof walkable)[number]) => boolean) =>
  Math.round((walkable.filter(f).reduce((t, e) => t + e.lengthM, 0) / total) * 1000) / 10;
const crossings = g.edges.filter((e) => e.kind === "crossing");
const kerbKnown = crossings.filter((e) =>
  [e.from, e.to].every((id) => {
    const n = g.nodes.find((x) => x.id === id);
    return n?.kerb && n.kerb.type.state !== "unknown";
  }),
).length;
md.push(
  "## Coverage in the spike area",
  "",
  `Footway network: ${(total / 1000).toFixed(1)} km.`,
  "",
  "| Attribute | Known (by length) |",
  "|---|---|",
  `| Incline | ${pct((e) => isKnown(e.attrs.incline) || e.kind === "steps")}% |`,
  `| Cross-slope | ${pct((e) => isKnown(e.attrs.crossSlope))}% |`,
  `| Surface | ${pct((e) => isKnown(e.attrs.surface))}% |`,
  `| Width | ${pct((e) => isKnown(e.attrs.width))}% |`,
  `| Separately mapped pavement (not a street centreline stand-in) | ${pct((e) => e.kind !== "street_proxy")}% |`,
  `| Crossings with both kerbs known | ${Math.round((kerbKnown / crossings.length) * 100)}% of ${crossings.length} |`,
  "",
);

writeFileSync(join(ROOT, "docs/spikes/phase0-edinburgh.md"), md.join("\n"));
writeFileSync(join(ROOT, "docs/spikes/phase0-edinburgh.geojson"), JSON.stringify({ type: "FeatureCollection", features }));
console.log(md.join("\n"));
